-- Transactions trend from urban/non-urban districts
SELECT count(trans_id) as TRANS_NUM, URBAN_RANK, MONTH_INTERVAL
FROM (SELECT TRANS_ID,
             NTILE(2) OVER (ORDER BY RATIO_URBAN DESC)                                  AS URBAN_RANK,
             EXTRACT(MONTH FROM CREATED_DATE) || '-' || EXTRACT(YEAR FROM CREATED_DATE) AS MONTH_INTERVAL
      FROM DMELISSO.TRANSACTIONS
               NATURAL JOIN DMELISSO.ACCOUNT
               NATURAL JOIN DMELISSO.DISPOSITION
               NATURAL JOIN DMELISSO.CLIENT
               NATURAL JOIN DMELISSO.DISTRICT_DETAIL) T
group by MONTH_INTERVAL, URBAN_RANK;

-- Transactions trend from (HIG,MIG,LIG) neighborhood districts
SELECT count(trans_id) as TRANS_NUM, INCOME_GROUP_RANK, MONTH_INTERVAL
FROM (SELECT TRANS_ID,
             NTILE(3) OVER (ORDER BY SALARY_AVERAGE DESC)                               AS INCOME_GROUP_RANK,
             EXTRACT(MONTH FROM CREATED_DATE) || '-' || EXTRACT(YEAR FROM CREATED_DATE) AS MONTH_INTERVAL
      FROM DMELISSO.TRANSACTIONS
               NATURAL JOIN DMELISSO.ACCOUNT
               NATURAL JOIN DMELISSO.DISPOSITION
               NATURAL JOIN DMELISSO.CLIENT
               NATURAL JOIN DMELISSO.DISTRICT_DETAIL) T
group by MONTH_INTERVAL, INCOME_GROUP_RANK;

-- Trend of card usage by type
SELECT count(trans_id) as TRANS_NUM, CARD_TYPE, MONTH_INTERVAL
FROM (SELECT TRANS_ID,
             C.TYPE                                                                     as card_type,
             EXTRACT(MONTH FROM CREATED_DATE) || '-' || EXTRACT(YEAR FROM CREATED_DATE) AS MONTH_INTERVAL
      FROM DMELISSO.TRANSACTIONS T
               JOIN DMELISSO.DISPOSITION D ON D.ACCOUNT_ID = T.ACCOUNT_ID
               JOIN DMELISSO.CARD C ON D.DISP_ID = C.DISP_ID) T
group by MONTH_INTERVAL, CARD_TYPE;


-- Trend of transaction by bracket of transaction amount, as in higher amount vs mid amount vs low amount account holders
SELECT count(trans_id) as TRANS_NUM, TRANS_AMOUNT_RANK, MONTH_INTERVAL
FROM (SELECT TRANS_ID,
             NTILE(3) OVER (ORDER BY AMOUNT DESC)                                       AS TRANS_AMOUNT_RANK,
             EXTRACT(MONTH FROM CREATED_DATE) || '-' || EXTRACT(YEAR FROM CREATED_DATE) AS MONTH_INTERVAL
      FROM DMELISSO.TRANSACTIONS
               NATURAL JOIN DMELISSO.ACCOUNT
               NATURAL JOIN DMELISSO.DISPOSITION
               NATURAL JOIN DMELISSO.CLIENT
               NATURAL JOIN DMELISSO.DISTRICT_DETAIL) T
group by MONTH_INTERVAL, TRANS_AMOUNT_RANK;

-- Trend of transaction by bracket of balance, as in higher balance vs mid balance vs low balance account holders
SELECT count(trans_id) as TRANS_NUM, ACCOUNT_BALANCE_RANK, MONTH_INTERVAL
FROM (SELECT T.TRANS_ID,
             ACCOUNT_BALANCE_RANK,
             EXTRACT(MONTH FROM T.CREATED_DATE) || '-' || EXTRACT(YEAR FROM T.CREATED_DATE) AS MONTH_INTERVAL
      FROM (SELECT ACCOUNT_ID,
                   NTILE(3) OVER (ORDER BY AVG_ACCOUNT_BALANCE DESC) AS ACCOUNT_BALANCE_RANK
            FROM (SELECT ACCOUNT_ID,
                         AVG(BALANCE) AS AVG_ACCOUNT_BALANCE
                  FROM DMELISSO.TRANSACTIONS
                  group by ACCOUNT_ID)) ACCOUNT_BALANCE_DETAILS
               JOIN DMELISSO.TRANSACTIONS T ON ACCOUNT_BALANCE_DETAILS.ACCOUNT_ID = T.ACCOUNT_ID) E
GROUP BY MONTH_INTERVAL, ACCOUNT_BALANCE_RANK;
